import type { LiveOSModule } from './types';
import { travelModule } from './travel/manifest';

export const MODULE_REGISTRY: LiveOSModule[] = [
  travelModule,
  {
    id: 'sport',
    name: 'Sport & Laufen',
    tagline: 'Halbmarathon 2026 — 500 km Jahresziel',
    icon: '🏃',
    color: 'green',
    href: '/sport',
    profileDataHref: '/api/modules/sport/profile-data',
    status: 'active',
  },
  {
    id: 'gaming',
    name: 'Gaming',
    tagline: '10-Slot Backlog — Jahresplan 2026',
    icon: '🎮',
    color: 'purple',
    href: '/gaming',
    profileDataHref: '/api/modules/gaming/profile-data',
    status: 'active',
  },
  {
    id: 'reading',
    name: 'Lesen & Hörbücher',
    tagline: '6 Bücher + 6 Hörbücher 2026',
    icon: '📚',
    color: 'amber',
    href: '/reading',
    profileDataHref: '/api/modules/reading/profile-data',
    status: 'active',
  },
  {
    id: 'finance',
    name: 'Finanzen',
    tagline: 'KK tilgen · Fixkosten · Sonderausgaben',
    icon: '💰',
    color: 'blue',
    href: '/finance',
    profileDataHref: '/api/modules/finance/profile-data',
    status: 'active',
  },
  {
    id: 'wedding',
    name: 'Hochzeit',
    tagline: 'Standesamt 10.10.2026 · Freie Trauung 2027',
    icon: '💍',
    color: 'red',
    href: '/wedding',
    profileDataHref: '/api/modules/wedding/profile-data',
    status: 'active',
  },
  {
    id: 'coaching',
    name: 'Coaching',
    tagline: 'Projekte, Klienten & Fortschritt',
    icon: '◎',
    color: 'indigo',
    href: '/coaching',
    profileDataHref: '/api/modules/coaching/profile-data',
    status: 'coming_soon',
  },
];
